printWidth: 120
tabWidth: 4
useTabs: true
semi: true
singleQuote: false
quoteProps: as-needed
trailingComma: none
bracketSpacing: true
bracketSameLine: true
arrowParens: always
endOfLine: lf
embeddedLanguageFormatting: auto
